### PR TITLE
Add `msgType` for pulling out the messagetype number for any message.

### PR DESCRIPTION
**Pull request by JoshuaGross**
Issues:
1) We should be using a classy lens so we can do `anyMsg ^. msgType`?
2) Should add test to roundtrip messages through the parser and verify that the msgType is correct

cc @swift-nav/skylark

### CODE REVIEW

**Comment by mfine** [comment]
Yeah, this was annoying. The spec moves the type into the messages, but it should really be lifted out.

**Comment by mfine** [comment]
There's a function `checkNum` that looks at the payload for the type. Should remove the types from the messages and have them part of `Msg`.

**Comment by mfine** [comment]
Looked into moving the message type out, but its messy because its part of the payload and it makes the payload handling funky.

Looked at adding `makeClassy` and having `RTCM3Msg` be an instance of `HasMsg` and its messy because of the sum type + product type mix. (there's likely a better way to represent these messages to make this possible...).

I don't like the big pattern match here. There's a function in `Types.hs` that returns the message number from the payload - `checkNum`. That's a bad function name - I'd rather rename that to `msgNum` (and rename `checkCrc` to `msgCrc`), and use that to derive the message number.

**Comment by JoshuaGross** [comment]
Closing in favor of #5

**Pull request closed without merging**
