### PR TITLE
GLONASS

### PR DESCRIPTION
**Pull request by mfine**
Add 1009, 1010, 1011, 1012, 1013, 1033, and 1230 message types.

Some light review would be great.

/cc @swift-nav/estimation @swift-nav/skylark

### CODE REVIEW

**Comment by ljbade** [comment]
Wow I love how clean this is in Haskell.

Feedback:
Message type 1005:
- change the galileo bit to reserved
- add the quarter cycle indicator field (uses a previous reserved bit)

**Comment by ljbade** [comment]
Interesting, message type 1013 might help solve the GPS week number problem in the RTCM to SBP converter. It might also provide a way to get statistics about what messages are present in streams.

**Comment by mfine** [comment]
Unfortunately, not seeing `1013` being sent consistently across stations :(

**Comment by mfine** [comment]
Oh god, nice find on `_antennaReference_oscillator` :( - need to add some serdes roundtrip checks to these tests sooner than later.

**Comment by mfine** [comment]
@ljbade picked up your changes in 8dbf923.

**Comment by mfine** [comment]
All messages now round tripped with property tests.

**Comment by mfine** [comment]
And working with travis. Bringing this in.

**Pull request merged**
